### ISSUE TITLE
Great start, but really make it look like the "pasta place", not an academic exercise...

### ISSUE THREAD

**Issue by jelkner** [evannol/pasta-place#1]
You are off to a great start, but please remove links with names like "Labs 1-3".  The goal is to build a beautiful looking website that is all about pasta.  I am hoping to see information about the history of pasta, the huge varieties of pasta around the world, etc.  Even though we know this is an academic exercise, we do not want to make that obvious to our viewers.

**Comment by evannol** [comment]
fixed
